// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udobsseytwzfnrwnwxyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb2Jzc2V5dHd6Zm5yd253eHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTAzNDgsImV4cCI6MjA2OTM2NjM0OH0.nCNuU7Jh1YeQDrtGaPG6rckpaIgtp1bgglPTVfGWvQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});